### ADD A Product post (user)
POST http://localhost:8080/api/v1/products
Authorization: bearer {{userJWT}}
Content-Type: application/json

{
  "productName": "Product B2ec8",
  "description": "Product 1 description",
  "pictures": ["https://www.google.com"],
  "price": 100,
  "category": "Category 1"


}

### Create new group
POST http://localhost:8080/api/v1/groups
Authorization: bearer {{userJWT}}
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="group"
Content-Type: application/json

{
  "name": "Group 1",
  "description": "Group 1 description"
}
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="imageFile"; filename="default_group_image.png"
Content-Type: image/png

< C:\Users\user\Desktop\dummy pictures for market project\default group image.png
------WebKitFormBoundary7MA4YWxkTrZu0gW--


### Update group by id
PUT http://localhost:8080/api/v1/groups/1
Authorization: bearer {{userJWT}}
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="updateDetails"
Content-Type: application/json

{
  "name": "Group 1",
  "description": "Group 1 description"
}
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="imageFile"; filename="group_pic_2.png"
Content-Type: image/png

< C:\Users\user\Desktop\dummy pictures for market project\group pic 2.png
------WebKitFormBoundary7MA4YWxkTrZu0gW--

### Create post in group
POST http://localhost:8080/api/v1/products/group/1
Authorization: bearer eyJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJzZWxmIiwic3ViIjoidXNlcjFAdXNlci5jb20iLCJleHAiOjE3MTk4NTg5NzgsImlhdCI6MTcxNzI2Njk3OCwic2NvcGUiOiJST0xFX1VTRVIifQ.Psgd46qVKG73Ea7ciCu_MU14TdnmLAnKpxjplkxfnSZeasnfTTncm6eIiGdF3W03i6PX7Etwb-QLyza_Bu-RQWhY29tVjZwUNjGIOh4NwaVLSvxigcMLSY125r_lyieSWMiKR2BYRE_LCG_nsj-JBoZp8NIohaMoJKMWf5gOubfVZop3_shsiTXZ4SowZx4Q38dbRJ2D_iHcITFJB-jBvtgJbp2K6lwCTSVtjY3jUsDhBog_sZ089TsjTAkgHdG8-lf7FHLnipQaLQZGRqeWH2dxSkHpuxcc-k5tx3flYzKxwEBl4HvZVi_xnYXsbvOj_Itof8AqDA_twBjTNsNkqQ
Content-Type: application/json

{
  "productName": "Product B2ec8qwe908",
  "description": "Product 1 description",
  "pictures": ["https://www.google.com"],
  "price": 100,
  "category": "Category 1"


}

### GET user group by id
GET http://localhost:8080/api/v1/groups/1
Authorization: Basic dXNlcjFAdXNlci5jb206UGFzc3cwcmQxIQ==

### register a new user
POST http://localhost:8080/api/v1/auth/register
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="user"
Content-Type: application/json

{
  "firstName": "user4",
  "lastName": "UserFourth",
  "phoneNumber": "+12304567891",
  "email": "smthelse@smth.smth",
  "location": "Jupiter",
  "password": "12345678Aa!"
}
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="profilePictureFile"; filename="default_user_pfp.jpg"
Content-Type: image/jpeg

< C:\Users\user\Desktop\dummy pictures for market project\default user pfp.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW--



### GET all posts
GET http://localhost:8080/api/v1/products
Authorization: bearer eyJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJzZWxmIiwiZXhwIjoxNzE5ODU2OTY3LCJpYXQiOjE3MTcyNjQ5NjcsInNjb3BlIjoiUk9MRV9VU0VSIn0.gTJYPMfopT-ER_40V-JRfZkNk5zud0f4Kbz_vn7Fc4oIVmxap-2vBtGQK5XSDcVC6ugAdIQI1jwM313T74bNq-c72O6rNXdMk-tRak8BeTigeVJQVglcNM6BiUyuZiXl3oYG9SJsmJN9tURA3yBRb0s-m7369C14k9VBpUSrAHNhAnZkldm7r1qsJ9po-V-Nu_hn6QmvXq86A3KclAB4SL9k-f9576MK3uWaJi60E6l7B_EQBKxFrc3qtTJBXZbkOpbm7u09cLSSxYIA3hLh-PyHa96sQZ4vxCS09NmdeXKtHXxQFmexwG7L1PyM_XYZvd_HgjZQCqEtSnUrA70OgQ

### GET user by id
GET http://localhost:8080/api/v1/users/3
Authorization: bearer {{adminJWT}}


### Request to join group
PUT http://localhost:8080/api/v1/users/2/sendJoinRequest
Authorization: Basic c210aEBzbXRoLnNtdGg6MTIzNDU2NzhBYSE=

### Accept request to join group
PUT http://localhost:8080/api/v1/groups/2/users/3/approve
Authorization: Basic dXNlcjFAdXNlci5jb206UGFzc3cwcmQxIQ==

### Login
POST http://localhost:8080/api/v1/auth/login
Content-Type: application/json

{
  "email": "user1@user.com",
  "password": "Passw0rd1!"
}

### DELETE user by id
DELETE http://localhost:8080/api/v1/users/3
Authorization: bearer {{adminJWT}}

### Update user by id
PUT http://localhost:8080/api/v1/users/3
Authorization: bearer {{user3JWT}}
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="updateDetails"
Content-Type: application/json

{
  "firstName": "user3.2.2",
  "lastName": "UserThird"

}
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="profilePictureFile"; filename="default_user_pfp.jpg"
Content-Type: image/jpeg

< C:\Users\user\Desktop\dummy pictures for market project\user pic 2.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW--

